version: '3.9'

services:

  qgis-processing:
      container_name: qgis-processing
      build:
        context: .
      volumes:
        - ./test-data:/test-data
        - ./app:/app
      env_file: ./.env
      ports:
        - "5000:5000"
      restart: always